# Generated by Django 4.0.3 on 2024-07-05 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('public_method', models.CharField(choices=[('time', '時刻公開'), ('immediate', 'すぐ公開'), ('hold', '保留')], default='time', max_length=20)),
                ('push', models.CharField(choices=[('push-on', '通知する'), ('push-off', '通知しない')], default='push-on', max_length=20)),
                ('issued_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pybo_table',
            },
        ),
    ]
